# docker-compose.yml
version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/nginx.dev.conf:/etc/nginx/nginx.conf"

  app:
    build:
      args:
        - BuildMode=development
    env_file:
      - .env
    volumes:
      - ./apps:/usr/app/apps
      - ./packages:/usr/app/packages
    command: yarn turbo run dev --filter=!native
    ports:
      - "19006:19006"
    environment:
      - PORT=19006

  native:
    build:
      context: .
      args:
        - BuildMode=development
    env_file:
      - .env
    volumes:
      - ./apps:/usr/app/apps
      - ./packages:/usr/app/packages
    command: sh -c "yarn workspace native start --port 19000 --clear"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=${EXPO_LOCAL_IP}
      - PORT=19000
      - NODE_OPTIONS=--max-old-space-size=4096

  prisma:
    image: timothyjmiller/prisma-studio:latest
    env_file:
      - .env.dockerdev.local
    environment:
      PROJECT_NAME: myturbo-project
      POSTGRES_HOST: postgres
      POSTGRES_URL: ${PRISMA_DATABASE_URL}
      POSTGRES_DATABASE: ${DATABASE_NAME}
      POSTGRES_USERNAME: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_PORT: 5432
      PRISMA_STUDIO_PORT: 5555
      POSTGRES_PATH: /postgres
    ports:
      - 5555:5555
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: