# setup ssl certificate on cloudflare
# https://support.cloudflare.com/hc/en-us/articles/200167836-Where-do-I-find-a-free-SSL-certificate-
# This script is based on https://gist.github.com/nikmartin/5902176
# It will create a self-signed certificate and install it on your server.

events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        access_log /var/log/nginx/access-dev.log;
        error_log /var/log/nginx/error-dev.log;

        location / {
            proxy_pass http://app:3000;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            # Cookies
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_read_timeout 5m;
            proxy_connect_timeout 5m;
            proxy_redirect off;
        }

        location /api/ {
            proxy_pass http://app:4000;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            # Cookies
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_read_timeout 5m;
            proxy_connect_timeout 5m;
            proxy_redirect off;
        }
    }
}
